import React from 'react';
import {
  Document,
  Page,
  View,
  Text,
  Fixed,
  Image,
  Badge,
} from './primitives';
import { createExecutiveTheme } from './theme';
import { MarkdownRenderer } from './MarkdownRenderer';

export interface ExecutiveReportData {
  agencyName: string;
  agencyLogoUrl?: string;
  clientName: string;
  targetDomain?: string;
  preparedBy: string;
  executiveNotes?: string;
  primaryColor?: string;
  markdownText: string;
  auditDate?: string;
}

export const ExecutiveReportDocument: React.FC<ExecutiveReportData> = ({
  agencyName,
  agencyLogoUrl,
  clientName,
  targetDomain,
  preparedBy,
  executiveNotes,
  primaryColor = '#BF953F',
  markdownText,
  auditDate,
}) => {
  const theme = createExecutiveTheme(primaryColor);
  const formattedDate =
    auditDate ||
    new Date().toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });

  return (
    <Document
      title={`${agencyName} - Strategic AEO Brief for ${clientName}`}
      author={agencyName}
      creator="Luminara Search Oracle"
      lang="en-US"
    >
      <Page
        size="A4"
        margin={{
          top: theme.spacing.pageMargin.top,
          bottom: theme.spacing.pageMargin.bottom,
          left: theme.spacing.pageMargin.left,
          right: theme.spacing.pageMargin.right,
        }}
        style={{
          backgroundColor: theme.colors.background,
          color: theme.colors.foreground,
        }}
      >
        {/* Fixed Footer on all pages */}
        <Fixed
          position="footer"
          style={{
            borderTopWidth: 1,
            borderTopColor: theme.colors.border,
            paddingTop: 8,
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            width: '100%',
          }}
        >
          <Text style={{ fontSize: theme.typography.sizes.xs, color: theme.colors.mutedForeground }}>
            Generated by {agencyName} • Enterprise Search Intelligence
          </Text>
          <Text style={{ fontSize: theme.typography.sizes.xs, color: theme.colors.mutedForeground }}>
            Strictly Confidential • Client Deliverable
          </Text>
        </Fixed>

        {/* Executive Header Section */}
        <View style={{ marginBottom: 14 }}>
          <View
            style={{
              flexDirection: 'row',
              justifyContent: 'space-between',
              alignItems: 'flex-start',
              marginBottom: 8,
            }}
          >
            {/* Left: Agency Info & Optional Logo */}
            <View style={{ flex: 1 }}>
              {agencyLogoUrl ? (
                <View style={{ marginBottom: 6 }}>
                  <Image
                    src={agencyLogoUrl}
                    height={32}
                    style={{ alignSelf: 'flex-start' }}
                  />
                </View>
              ) : null}
              <Text
                style={{
                  fontSize: theme.typography.sizes.xxl,
                  fontWeight: 700,
                  color: theme.colors.foreground,
                  letterSpacing: -0.5,
                }}
              >
                {agencyName}
              </Text>
              <Text style={{ fontSize: theme.typography.sizes.sm, color: theme.colors.mutedForeground }}>
                {preparedBy}
              </Text>
            </View>

            {/* Right: Meta Details & Security Pill */}
            <View style={{ alignItems: 'flex-end' }}>
              <Badge label="Strict Privilege" tone="primary" theme={theme} style={{ marginBottom: 4 }} />
              <Text style={{ fontSize: theme.typography.sizes.xs, color: theme.colors.mutedForeground }}>
                Target: {clientName} {targetDomain ? `(${targetDomain})` : ''}
              </Text>
              <Text style={{ fontSize: theme.typography.sizes.xs, color: theme.colors.mutedForeground }}>
                Date: {formattedDate}
              </Text>
            </View>
          </View>

          {/* Accent Gold Banner Divider */}
          <View
            style={{
              height: 3,
              backgroundColor: theme.colors.primary,
              width: '100%',
              borderRadius: 2,
              marginVertical: 6,
            }}
          />
        </View>

        {/* Report Title & Subtitle */}
        <View style={{ marginBottom: 12 }}>
          <Text
            style={{
              fontSize: theme.typography.sizes.title,
              fontWeight: 700,
              color: theme.colors.foreground,
              letterSpacing: -0.5,
              marginBottom: 3,
            }}
          >
            AEO & Search Intelligence Audit
          </Text>
          <Text style={{ fontSize: theme.typography.sizes.sm, color: theme.colors.mutedForeground }}>
            Prepared exclusively for executive leadership at {clientName}
          </Text>
        </View>

        {/* Strategic Context Callout Banner */}
        {executiveNotes ? (
          <View
            wrap={false}
            style={{
              borderLeftWidth: 3.5,
              borderLeftColor: theme.colors.primary,
              backgroundColor: theme.colors.muted,
              padding: 10,
              borderRadius: 4,
              marginBottom: 14,
            }}
          >
            <Text
              style={{
                fontSize: theme.typography.sizes.xs,
                fontWeight: 700,
                color: theme.colors.primary,
                textTransform: 'uppercase',
                marginBottom: 3,
                letterSpacing: 0.5,
              }}
            >
              Executive Strategic Context
            </Text>
            <Text
              style={{
                fontSize: theme.typography.sizes.base,
                color: theme.colors.foreground,
                lineHeight: 1.45,
              }}
            >
              {executiveNotes}
            </Text>
          </View>
        ) : null}

        {/* Report Body (Markdown to Native PDF) */}
        <View style={{ marginTop: 4 }}>
          <MarkdownRenderer content={markdownText} theme={theme} />
        </View>
      </Page>
    </Document>
  );
};
