import React, { useState, useEffect } from 'react';
import { ICONS } from '../../constants';
import {
  CmsPlatform,
  DeploymentConfig,
  DeploymentResult,
  RemediationPayload,
  cmsDeploymentService,
} from '../../services/deployment/cmsDeploymentService';
import { writingQualityService, type WritingQualityReport } from '../../services/audit/writingQualityService';
import { schemaSafetyGate, type SchemaSafetyResult } from '../../services/deployment/schemaSafetyGate';

interface CmsDeploymentModalProps {
  isOpen: boolean;
  onClose: () => void;
  remediationPayload?: RemediationPayload;
}

export const CmsDeploymentModal: React.FC<CmsDeploymentModalProps> = ({
  isOpen,
  onClose,
  remediationPayload,
}) => {
  const [platform, setPlatform] = useState<CmsPlatform>('wordpress');
  const [saveCreds, setSaveCreds] = useState(true);
  const [deploying, setDeploying] = useState(false);
  const [result, setResult] = useState<DeploymentResult | null>(null);
  const [historyOpen, setHistoryOpen] = useState(false);
  const [copiedScript, setCopiedScript] = useState(false);

  // Form states
  const [endpoint, setEndpoint] = useState('');
  const [authToken, setAuthToken] = useState('');
  const [siteId, setSiteId] = useState('');
  const [repoOwner, setRepoOwner] = useState('');
  const [repoName, setRepoName] = useState('');
  const [targetBranch, setTargetBranch] = useState('main');
  const [filePath, setFilePath] = useState('app/layout.tsx');

  // Load stored config when platform switches
  useEffect(() => {
    if (!isOpen) return;
    const cfg = cmsDeploymentService.getSavedConfig(platform);
    setEndpoint(cfg.endpoint || (remediationPayload?.domain ? `https://${remediationPayload.domain}` : ''));
    setAuthToken(cfg.authToken || '');
    setSiteId(cfg.siteId || '');
    setRepoOwner(cfg.repoOwner || '');
    setRepoName(cfg.repoName || '');
    setTargetBranch(cfg.targetBranch || 'main');
    setFilePath(cfg.filePath || (platform === 'github_pr' ? 'app/layout.tsx' : ''));
    setResult(null);
  }, [platform, isOpen, remediationPayload]);

  // Writing check on the human-readable text inside the schema (best-effort, never blocks deploy).
  const [writingCheck, setWritingCheck] = useState<WritingQualityReport | null>(null);
  const [writingLoading, setWritingLoading] = useState(false);
  const [writingOpen, setWritingOpen] = useState(false);
  const schemaJsonLd = remediationPayload?.schemaJsonLd;
  useEffect(() => {
    if (!isOpen || !schemaJsonLd) {
      setWritingCheck(null);
      setWritingLoading(false);
      setWritingOpen(false);
      return;
    }
    let cancelled = false;
    setWritingLoading(true);
    setWritingCheck(null);
    setWritingOpen(false);
    writingQualityService
      .checkSchemaText(schemaJsonLd)
      .then(r => { if (!cancelled) setWritingCheck(r); })
      .catch(() => { if (!cancelled) setWritingCheck(null); })
      .finally(() => { if (!cancelled) setWritingLoading(false); });
    return () => { cancelled = true; };
  }, [isOpen, schemaJsonLd]);

  if (!isOpen) return null;

  const defaultPayload: RemediationPayload = remediationPayload || {
    domain: 'yourbrand.com',
    title: 'AEO Entity Remediation',
    schemaJsonLd: JSON.stringify({
      "@context": "https://schema.org",
      "@graph": [
        {
          "@type": "Organization",
          "name": "Target Brand",
          "description": "Authoritative entity representation generated by Luminara Search Oracle Agent."
        }
      ]
    }, null, 2)
  };

  const schemaGate: SchemaSafetyResult = schemaSafetyGate.validate(defaultPayload.schemaJsonLd);
  const deployBlocked = !schemaGate.okToDeploy;

  const handleDeploy = async () => {
    if (deployBlocked && platform !== 'script_tag') {
      setResult({
        success: false,
        platform,
        deploymentId: `gate-${Date.now()}`,
        message: `Schema safety gate blocked deploy: ${schemaGate.issues
          .filter((i) => i.severity === 'critical')
          .map((i) => i.message)
          .join(' ')}`,
        diffSummary: { linesAdded: 0, linesRemoved: 0 },
        timestamp: Date.now(),
        validationErrors: schemaGate.issues,
        gateSeverity: schemaGate.severity,
      });
      return;
    }

    setDeploying(true);
    setResult(null);

    const config: DeploymentConfig = {
      platform,
      endpoint: endpoint.trim(),
      authToken: authToken.trim(),
      siteId: siteId.trim(),
      repoOwner: repoOwner.trim(),
      repoName: repoName.trim(),
      targetBranch: targetBranch.trim() || 'main',
      filePath: filePath.trim() || 'app/layout.tsx',
    };

    if (saveCreds) {
      cmsDeploymentService.saveConfig(platform, config);
    }

    try {
      let res: DeploymentResult;
      switch (platform) {
        case 'wordpress':
          res = await cmsDeploymentService.deployToWordPress(config, defaultPayload);
          break;
        case 'webflow':
          res = await cmsDeploymentService.deployToWebflow(config, defaultPayload);
          break;
        case 'github_pr':
          res = await cmsDeploymentService.deployToGitHubPR(config, defaultPayload);
          break;
        case 'shopify':
        case 'script_tag':
        default:
          res = {
            success: schemaGate.okToDeploy,
            platform: 'script_tag',
            deploymentId: `cdn-${Date.now()}`,
            message: schemaGate.okToDeploy
              ? 'Zero-code CDN script generated and verified ready for site insertion.'
              : `Script generated with Critical schema issues: ${schemaGate.issues
                  .filter((i) => i.severity === 'critical')
                  .map((i) => i.code)
                  .join(', ')}. Review before pasting.`,
            diffSummary: { linesAdded: defaultPayload.schemaJsonLd.split('\n').length, linesRemoved: 0 },
            timestamp: Date.now(),
            validationErrors: schemaGate.issues,
            gateSeverity: schemaGate.severity,
          };
          break;
      }
      setResult(res);
    } catch (err: any) {
      setResult({
        success: false,
        platform,
        deploymentId: `err-${Date.now()}`,
        message: err?.message || 'Deployment dispatch failed.',
        diffSummary: { linesAdded: 0, linesRemoved: 0 },
        timestamp: Date.now(),
      });
    } finally {
      setDeploying(false);
    }
  };

  const scriptTagCode = cmsDeploymentService.generateClientScriptTag(defaultPayload);

  const handleCopyScript = () => {
    navigator.clipboard.writeText(scriptTagCode);
    setCopiedScript(true);
    setTimeout(() => setCopiedScript(false), 2000);
  };

  const history = cmsDeploymentService.getDeploymentHistory();

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md animate-in fade-in duration-200">
      <div className="relative w-full max-w-3xl glass-morphism rounded-2xl border border-gold/40 shadow-2xl flex flex-col max-h-[90vh] overflow-hidden bg-black/95">
        
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-white/10 bg-black/60">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-lg bg-gradient-to-br from-gold/20 to-gold-dark/10 text-gold-light border border-gold/30">
              <ICONS.Zap className="w-5 h-5 text-gold-light" />
            </div>
            <div>
              <h3 className="text-base font-bold text-white tracking-wide flex items-center gap-2">
                1-Click CMS & GitHub Autonomous Deployment
              </h3>
              <p className="text-xs text-gray-400">
                Deploy remediated Schema.org markup directly into production code.
              </p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="p-1.5 rounded-lg text-gray-400 hover:text-white hover:bg-white/5 transition-colors"
          >
            <ICONS.X className="w-5 h-5" />
          </button>
        </div>

        {/* Content Body */}
        <div className="flex-1 p-6 overflow-y-auto space-y-6">

          {(schemaGate.severity === 'critical' || schemaGate.severity === 'warn') && (
            <div
              className={`rounded-xl border p-3 text-xs ${
                schemaGate.severity === 'critical'
                  ? 'border-danger-500/40 bg-danger-500/10 text-danger-200'
                  : 'border-warning-500/40 bg-warning-500/10 text-warning-200'
              }`}
            >
              <div className="font-bold uppercase tracking-wider text-[10px] mb-1">
                Schema Safety Gate: {schemaGate.severity}
              </div>
              <ul className="space-y-1 list-disc pl-4">
                {schemaGate.issues.map((issue, idx) => (
                  <li key={idx}>
                    <span className="font-mono">[{issue.code}]</span> {issue.message}
                  </li>
                ))}
              </ul>
            </div>
          )}
          
          {/* Target Platform Selector */}
          <div>
            <label className="block text-xs font-bold uppercase tracking-widest text-gray-400 mb-2">
              Target CMS / Infrastructure
            </label>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
              {[
                { id: 'wordpress', label: 'WordPress', hint: 'REST API' },
                { id: 'webflow', label: 'Webflow', hint: 'Sites API v2' },
                { id: 'github_pr', label: 'GitHub PR', hint: 'Automated PR' },
                { id: 'script_tag', label: 'Script Tag', hint: 'Zero-Code CDN' },
              ].map((item) => (
                <button
                  key={item.id}
                  onClick={() => setPlatform(item.id as CmsPlatform)}
                  className={`p-3 rounded-xl border text-left transition-all ${
                    platform === item.id
                      ? 'bg-gold/20 border-gold shadow-lg shadow-gold/10'
                      : 'border-white/10 hover:border-white/20 glass-morphism text-gray-400 hover:text-white'
                  }`}
                >
                  <div className={`text-xs font-bold ${platform === item.id ? 'text-gold-light' : 'text-gray-200'}`}>
                    {item.label}
                  </div>
                  <div className="text-[10px] text-gray-500 font-mono mt-0.5">{item.hint}</div>
                </button>
              ))}
            </div>
          </div>

          {/* Form Configuration based on platform */}
          {platform === 'wordpress' && (
            <div className="space-y-4 glass-morphism p-4 rounded-xl border border-white/10">
              <div>
                <label className="block text-[11px] font-bold text-gray-300 uppercase tracking-wider mb-1">
                  WordPress Site URL
                </label>
                <input
                  type="text"
                  value={endpoint}
                  onChange={(e) => setEndpoint(e.target.value)}
                  placeholder="https://yourblog.com"
                  className="w-full bg-black/60 border border-white/15 focus:border-gold rounded-lg px-3 py-2 text-xs text-white font-mono placeholder:text-gray-600 focus:outline-none"
                />
              </div>
              <div>
                <label className="block text-[11px] font-bold text-gray-300 uppercase tracking-wider mb-1">
                  Application Password or Basic Auth Token
                </label>
                <input
                  type="password"
                  value={authToken}
                  onChange={(e) => setAuthToken(e.target.value)}
                  placeholder="e.g. abcd efgh ijkl mnop (Generated in WP Users > Profile)"
                  className="w-full bg-black/60 border border-white/15 focus:border-gold rounded-lg px-3 py-2 text-xs text-white font-mono placeholder:text-gray-600 focus:outline-none"
                />
                <span className="text-[10px] text-gray-500 mt-1 block">
                  Generate in WordPress Admin &rarr; Users &rarr; Profile &rarr; Application Passwords.
                </span>
              </div>
            </div>
          )}

          {platform === 'webflow' && (
            <div className="space-y-4 glass-morphism p-4 rounded-xl border border-white/10">
              <div>
                <label className="block text-[11px] font-bold text-gray-300 uppercase tracking-wider mb-1">
                  Webflow Site ID
                </label>
                <input
                  type="text"
                  value={siteId}
                  onChange={(e) => setSiteId(e.target.value)}
                  placeholder="e.g. 64b123... (From Site Settings URL)"
                  className="w-full bg-black/60 border border-white/15 focus:border-gold rounded-lg px-3 py-2 text-xs text-white font-mono placeholder:text-gray-600 focus:outline-none"
                />
              </div>
              <div>
                <label className="block text-[11px] font-bold text-gray-300 uppercase tracking-wider mb-1">
                  Webflow API Token (Bearer)
                </label>
                <input
                  type="password"
                  value={authToken}
                  onChange={(e) => setAuthToken(e.target.value)}
                  placeholder="Webflow Workspace API token"
                  className="w-full bg-black/60 border border-white/15 focus:border-gold rounded-lg px-3 py-2 text-xs text-white font-mono placeholder:text-gray-600 focus:outline-none"
                />
              </div>
            </div>
          )}

          {platform === 'github_pr' && (
            <div className="space-y-4 glass-morphism p-4 rounded-xl border border-white/10">
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                <div>
                  <label className="block text-[11px] font-bold text-gray-300 uppercase tracking-wider mb-1">
                    GitHub Owner / Org
                  </label>
                  <input
                    type="text"
                    value={repoOwner}
                    onChange={(e) => setRepoOwner(e.target.value)}
                    placeholder="e.g. LuminaraDigital"
                    className="w-full bg-black/60 border border-white/15 focus:border-gold rounded-lg px-3 py-2 text-xs text-white font-mono placeholder:text-gray-600 focus:outline-none"
                  />
                </div>
                <div>
                  <label className="block text-[11px] font-bold text-gray-300 uppercase tracking-wider mb-1">
                    Repository Name
                  </label>
                  <input
                    type="text"
                    value={repoName}
                    onChange={(e) => setRepoName(e.target.value)}
                    placeholder="e.g. corporate-portal"
                    className="w-full bg-black/60 border border-white/15 focus:border-gold rounded-lg px-3 py-2 text-xs text-white font-mono placeholder:text-gray-600 focus:outline-none"
                  />
                </div>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                <div>
                  <label className="block text-[11px] font-bold text-gray-300 uppercase tracking-wider mb-1">
                    Base Branch
                  </label>
                  <input
                    type="text"
                    value={targetBranch}
                    onChange={(e) => setTargetBranch(e.target.value)}
                    placeholder="main"
                    className="w-full bg-black/60 border border-white/15 focus:border-gold rounded-lg px-3 py-2 text-xs text-white font-mono placeholder:text-gray-600 focus:outline-none"
                  />
                </div>
                <div>
                  <label className="block text-[11px] font-bold text-gray-300 uppercase tracking-wider mb-1">
                    Target File Path
                  </label>
                  <input
                    type="text"
                    value={filePath}
                    onChange={(e) => setFilePath(e.target.value)}
                    placeholder="app/layout.tsx or index.html"
                    className="w-full bg-black/60 border border-white/15 focus:border-gold rounded-lg px-3 py-2 text-xs text-white font-mono placeholder:text-gray-600 focus:outline-none"
                  />
                </div>
              </div>

              <div>
                <label className="block text-[11px] font-bold text-gray-300 uppercase tracking-wider mb-1">
                  Personal Access Token (PAT)
                </label>
                <input
                  type="password"
                  value={authToken}
                  onChange={(e) => setAuthToken(e.target.value)}
                  placeholder="ghp_xxxxxxxxxxxx (Requires repo scope)"
                  className="w-full bg-black/60 border border-white/15 focus:border-gold rounded-lg px-3 py-2 text-xs text-white font-mono placeholder:text-gray-600 focus:outline-none"
                />
              </div>
            </div>
          )}

          {platform === 'script_tag' && (
            <div className="space-y-3 glass-morphism p-4 rounded-xl border border-white/10">
              <div className="flex items-center justify-between">
                <span className="text-xs font-bold text-gold-light uppercase tracking-wider">
                  Zero-Code Universal Head Script
                </span>
                <button
                  onClick={handleCopyScript}
                  className="px-2.5 py-1 rounded bg-gold/20 text-gold-light hover:bg-gold/30 text-[11px] font-mono flex items-center gap-1 transition-colors"
                >
                  {copiedScript ? <ICONS.Check className="w-3.5 h-3.5 text-success-400" /> : <ICONS.Copy className="w-3.5 h-3.5" />}
                  {copiedScript ? 'Copied' : 'Copy Tag'}
                </button>
              </div>
              <p className="text-[11px] text-gray-400">
                Paste this single script tag into Google Tag Manager, Shopify theme.liquid, Webflow Custom Code, or any site header.
              </p>
              <pre className="p-3 bg-black/80 rounded-lg text-[11px] font-mono text-cyan-300 overflow-x-auto border border-white/5 whitespace-pre-wrap select-all">
                {scriptTagCode}
              </pre>
            </div>
          )}

          {/* Writing check on the schema text */}
          {schemaJsonLd && (writingLoading || (writingCheck && writingCheck.available)) && (
            <div className="p-3 rounded-xl glass-morphism border border-white/10 text-xs">
              {writingLoading ? (
                <p className="text-gray-400 flex items-center gap-2">
                  <span className="w-3 h-3 rounded-full border border-gold/30 border-t-gold animate-spin shrink-0"></span>
                  Proofreading the text in your schema…
                </p>
              ) : writingCheck && writingCheck.issues.length === 0 ? (
                <p className="text-success-300 flex items-center gap-2">
                  <ICONS.CheckCircle className="w-4 h-4 shrink-0" />
                  The text in your schema reads well.
                </p>
              ) : writingCheck ? (
                <div>
                  <div className="flex items-center justify-between gap-3">
                    <p className="text-warning-300 flex items-center gap-2">
                      <ICONS.AlertTriangle className="w-4 h-4 shrink-0" />
                      {writingCheck.issues.length.toLocaleString()} wording issue{writingCheck.issues.length === 1 ? '' : 's'} in your schema
                    </p>
                    <button
                      type="button"
                      onClick={() => setWritingOpen(v => !v)}
                      aria-expanded={writingOpen}
                      className="text-[11px] font-bold text-gold-light hover:underline flex items-center gap-1 shrink-0"
                    >
                      {writingOpen ? 'Hide' : 'Show'}
                      <ICONS.ChevronDown className={`w-3 h-3 transition-transform ${writingOpen ? 'rotate-180' : ''}`} />
                    </button>
                  </div>
                  {writingOpen && (
                    <ul className="mt-2.5 space-y-2 pl-2 border-l border-white/10">
                      {writingCheck.issues.slice(0, 8).map(issue => (
                        <li key={issue.id} className="text-gray-300 leading-snug">
                          {issue.field && <span className="font-mono text-[10px] text-gray-500">{issue.field}: </span>}
                          <span>{issue.message}</span>
                          {issue.suggestion && <span className="block text-[11px] text-gold-light">Try: {issue.suggestion}</span>}
                        </li>
                      ))}
                    </ul>
                  )}
                </div>
              ) : null}
            </div>
          )}

          {/* Credentials Saving Toggle */}
          {platform !== 'script_tag' && (
            <label className="flex items-center gap-2 cursor-pointer select-none text-xs text-gray-400">
              <input
                type="checkbox"
                checked={saveCreds}
                onChange={(e) => setSaveCreds(e.target.checked)}
                className="rounded border-white/20 bg-black text-gold focus:ring-0"
              />
              <span>Remember configuration credentials locally in this browser</span>
            </label>
          )}

          {/* Result Alert */}
          {result && (
            <div
              className={`p-4 rounded-xl border text-xs animate-in fade-in duration-300 ${
                result.success
                  ? 'bg-success-950/40 border-success-500/40 text-success-200'
                  : 'bg-danger-950/40 border-danger-500/40 text-danger-200'
              }`}
            >
              <div className="flex items-start justify-between gap-3">
                <div className="flex items-start gap-2.5">
                  {result.success ? (
                    <ICONS.CheckCircle className="w-5 h-5 text-success-400 shrink-0 mt-0.5" />
                  ) : (
                    <ICONS.AlertTriangle className="w-5 h-5 text-danger-400 shrink-0 mt-0.5" />
                  )}
                  <div>
                    <strong className="block text-sm font-bold text-white mb-0.5">
                      {result.success ? 'Autonomous Action Dispatched' : 'Deployment Error'}
                    </strong>
                    <p className="leading-relaxed">{result.message}</p>
                    {result.prUrl && (
                      <a
                        href={result.prUrl}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="mt-2 inline-flex items-center gap-1 text-gold-light hover:underline font-mono text-[11px]"
                      >
                        View Pull Request on GitHub &rarr;
                      </a>
                    )}
                  </div>
                </div>
                <span className="text-[10px] font-mono opacity-60 shrink-0">
                  +{result.diffSummary.linesAdded} lines
                </span>
              </div>
            </div>
          )}

          {/* Past History Accordion */}
          {history.length > 0 && (
            <div className="border-t border-white/10 pt-4">
              <button
                onClick={() => setHistoryOpen(!historyOpen)}
                className="flex items-center justify-between w-full text-xs font-bold text-gray-400 hover:text-white uppercase tracking-wider"
              >
                <span>Recent Autonomous Deployments ({history.length})</span>
                <ICONS.ChevronDown className={`w-4 h-4 transition-transform ${historyOpen ? 'rotate-180' : ''}`} />
              </button>

              {historyOpen && (
                <div className="mt-3 space-y-2 max-h-40 overflow-y-auto pr-1">
                  {history.map((h, i) => (
                    <div
                      key={i}
                      className="p-2.5 rounded-lg glass-morphism border border-white/5 flex items-center justify-between text-[11px]"
                    >
                      <div className="flex items-center gap-2">
                        <span className={`w-1.5 h-1.5 rounded-full ${h.success ? 'bg-success-400' : 'bg-danger-400'}`}></span>
                        <span className="font-mono text-gray-300 uppercase">{h.platform}</span>
                        <span className="text-gray-500 truncate max-w-[200px]">{h.message}</span>
                      </div>
                      <span className="text-[10px] font-mono text-gray-500">
                        {new Date(h.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                      </span>
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}

        </div>

        {/* Footer */}
        <div className="flex items-center justify-between px-6 py-4 border-t border-white/10 bg-black/70">
          <button
            onClick={onClose}
            className="px-4 py-2 rounded-xl glass-morphism border border-white/10 text-xs font-bold text-gray-300 hover:text-white uppercase tracking-wider transition-colors"
          >
            Cancel
          </button>

          {platform === 'script_tag' ? (
            <button
              onClick={handleCopyScript}
              className="px-5 py-2 rounded-xl bg-gradient-to-r from-gold to-gold-dark text-black font-black uppercase text-xs tracking-wider hover:scale-105 active:scale-95 transition-all shadow-lg shadow-gold/20 flex items-center gap-2"
            >
              <ICONS.Copy className="w-4 h-4" />
              <span>Copy Script Tag</span>
            </button>
          ) : (
            <button
              onClick={handleDeploy}
              disabled={deploying || deployBlocked}
              className="px-5 py-2 rounded-xl bg-gradient-to-r from-gold to-gold-dark text-black font-black uppercase text-xs tracking-wider hover:scale-105 active:scale-95 transition-all shadow-lg shadow-gold/20 flex items-center gap-2 disabled:opacity-40"
            >
              <ICONS.Zap className="w-4 h-4" />
              <span>
                {deploying
                  ? 'Deploying...'
                  : deployBlocked
                    ? 'Blocked by Schema Gate'
                    : `Deploy to ${platform.replace('_', ' ').toUpperCase()}`}
              </span>
            </button>
          )}
        </div>

      </div>
    </div>
  );
};
