import React from 'react';

interface Props {
  kind: 'privacy' | 'terms';
  onBack: () => void;
}

const UPDATED = '7 September 2026';

/**
 * Plain-language Privacy and Terms pages. Keep these truthful to how the app actually works:
 * keys in the browser, optional Telegram sign-in, hosted keys metered per user, AGPL-3.0 code.
 */
export const LegalPage: React.FC<Props> = ({ kind, onBack }) => {
  const isPrivacy = kind === 'privacy';
  return (
    <div className="min-h-screen bg-black text-gray-300">
      <div className="max-w-3xl mx-auto px-6 py-12">
        <button onClick={onBack} className="text-[10px] uppercase tracking-[0.3em] font-black text-gold hover:text-gold-light mb-10">← Back</button>
        <h1 className="text-3xl md:text-4xl font-semibold gold-text mb-2">{isPrivacy ? 'Privacy Policy' : 'Terms of Service'}</h1>
        <p className="text-xs text-gray-500 mb-10">Luminara Suite · Last updated {UPDATED}</p>

        {isPrivacy ? (
          <div className="space-y-8 text-sm leading-relaxed">
            <section>
              <h2 className="text-gold-light font-bold uppercase tracking-widest text-xs mb-2">What we store</h2>
              <p>Your API keys, Business DNA, chat history, themes and context graph are stored in your own browser (localStorage and sessionStorage). They are not uploaded to Luminara servers.</p>
            </section>
            <section>
              <h2 className="text-gold-light font-bold uppercase tracking-widest text-xs mb-2">What leaves your browser</h2>
              <p>When you run an audit or ask Oracle Agent, your prompt, the URL you entered and any Business DNA you linked are sent to the AI and search providers you configured (Groq, NVIDIA, Ollama, Google, Tavily, Firecrawl, Exa). Their privacy policies apply to that data. If you use your own keys, the request goes directly to the vendor, except NVIDIA NIM which is relayed through our server without being stored.</p>
            </section>
            <section>
              <h2 className="text-gold-light font-bold uppercase tracking-widest text-xs mb-2">Telegram</h2>
              <p>Inside Telegram we receive the signed launch data Telegram provides (your Telegram ID, name, username and language). We use it to identify you, meter free usage and record subscriptions paid with Telegram Stars. We keep your Telegram ID, plan, payment charge ID and expiry date. We do not receive your phone number or payment method.</p>
            </section>
            <section>
              <h2 className="text-gold-light font-bold uppercase tracking-widest text-xs mb-2">Wallets</h2>
              <p>Connecting a TON wallet shares your wallet address with the app in your browser. We do not custody funds or store private keys.</p>
            </section>
            <section>
              <h2 className="text-gold-light font-bold uppercase tracking-widest text-xs mb-2">Analytics and cookies</h2>
              <p>We do not set tracking cookies. Cloudflare, which hosts the service, records standard request logs for security and reliability.</p>
            </section>
            <section>
              <h2 className="text-gold-light font-bold uppercase tracking-widest text-xs mb-2">Your choices</h2>
              <p>Clear your browser storage to remove everything held locally. Message the bot with /status to see what we hold for your Telegram account, or email privacy@luminarasuite.com to have it deleted.</p>
            </section>
          </div>
        ) : (
          <div className="space-y-8 text-sm leading-relaxed">
            <section>
              <h2 className="text-gold-light font-bold uppercase tracking-widest text-xs mb-2">The service</h2>
              <p>Luminara Suite produces AI-assisted search, answer-engine and generative-engine audits and related tools. Outputs are generated by third-party language models from the evidence available at the time and can be wrong or incomplete. They are information, not professional advice, and you are responsible for decisions you make with them.</p>
            </section>
            <section>
              <h2 className="text-gold-light font-bold uppercase tracking-widest text-xs mb-2">Labs features</h2>
              <p>Screens marked "Labs" (OracleMind, TimesFM, the Archy harness) are demonstrations. Their numbers are simulated for illustration and must not be relied on as measurements.</p>
            </section>
            <section>
              <h2 className="text-gold-light font-bold uppercase tracking-widest text-xs mb-2">Your keys and accounts</h2>
              <p>You may use your own provider API keys. You are responsible for those accounts, their costs and their terms. Hosted keys on luminarasuite.com are provided to signed-in users within the free daily allowance or an active plan, and may be rate-limited or withdrawn to prevent abuse.</p>
            </section>
            <section>
              <h2 className="text-gold-light font-bold uppercase tracking-widest text-xs mb-2">Plans and payments</h2>
              <p>Plans bought with Telegram Stars run for the stated number of days from purchase and do not renew automatically. Refunds follow Telegram's Stars policy; contact support@luminarasuite.com for problems with a purchase.</p>
            </section>
            <section>
              <h2 className="text-gold-light font-bold uppercase tracking-widest text-xs mb-2">Acceptable use</h2>
              <p>Do not use the service to attack, scrape abusively, or misrepresent third parties, and do not attempt to extract hosted credentials. We may suspend access for abuse.</p>
            </section>
            <section>
              <h2 className="text-gold-light font-bold uppercase tracking-widest text-xs mb-2">Open source and trademarks</h2>
              <p>The Luminara Suite source code is licensed under the GNU AGPL-3.0. "Luminara", "Luminara Suite" and the Luminara logo are trademarks of Luminara Digital Agency and are not covered by the code license.</p>
            </section>
            <section>
              <h2 className="text-gold-light font-bold uppercase tracking-widest text-xs mb-2">Liability</h2>
              <p>The service is provided "as is". To the extent permitted by law, Luminara Digital Agency is not liable for indirect or consequential losses arising from use of the service.</p>
            </section>
          </div>
        )}
      </div>
    </div>
  );
};
