/**
 * Static Terms of Service HTML served by the Worker (same pattern as privacy).
 * Matches LegalPage terms sections. Not counsel-approved legal advice.
 */
export const TERMS_HTML = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Terms of Service | Luminara Suite</title>
  <meta name="description" content="Terms of Service for Luminara Suite web app, Telegram Mini App, and related APIs.">
  <meta name="theme-color" content="#0a0a0a">
  <meta property="og:title" content="Terms of Service | Luminara Suite">
  <meta property="og:description" content="Terms of Service for Luminara Suite.">
  <meta property="og:type" content="website">
  <meta property="og:url" content="https://www.luminarasuite.com/terms">
  <meta property="og:image" content="https://www.luminarasuite.com/icon-512.png">
  <link rel="canonical" href="https://www.luminarasuite.com/terms">
  <link rel="icon" href="/favicon.ico" sizes="48x48 32x32 16x16">
  <link rel="icon" type="image/png" sizes="48x48" href="/favicon-48.png">
  <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
  <style>
    body { font-family: system-ui, sans-serif; background: #0a0a0a; color: #e2e8f0; line-height: 1.65; max-width: 42rem; margin: 0 auto; padding: 2rem 1.25rem 4rem; }
    a { color: #BF953F; }
    h1 { font-size: 1.75rem; margin: 0 0 0.5rem; color: #FCF6BA; }
    h2 { font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.12em; color: #BF953F; margin: 1.75rem 0 0.5rem; }
    .meta { font-size: 0.8rem; color: #94a3b8; margin-bottom: 1.5rem; }
    p { margin: 0 0 0.75rem; color: #cbd5e1; font-size: 0.95rem; }
    nav a { margin-right: 1rem; font-size: 0.8rem; text-decoration: none; }
    footer { margin-top: 2.5rem; font-size: 0.75rem; color: #64748b; }
  </style>
</head>
<body>
  <nav>
    <a href="/">Home</a>
    <a href="/privacy">Privacy</a>
    <a href="/pricing">Pricing</a>
  </nav>
  <h1>Terms of Service</h1>
  <p class="meta">Luminara Suite · Operated by Luminara Digital Agency · Last updated 10 September 2026</p>
  <main>
    <h2>The service</h2>
    <p>Luminara Suite produces AI-assisted search, answer-engine and generative-engine audits and related tools. Outputs are generated by third-party language models from the evidence available at the time and can be wrong or incomplete. They are information, not professional advice, and you are responsible for decisions you make with them.</p>
    <h2>Labs features</h2>
    <p>Screens marked "Labs" (OracleMind, TimesFM, the Archy harness) are demonstrations. Their numbers are simulated for illustration and must not be relied on as measurements. Labs stay behind developer tools in the default product path.</p>
    <h2>Your keys and accounts</h2>
    <p>You may use your own provider API keys. You are responsible for those accounts, their costs and their terms. Hosted keys on luminarasuite.com are provided to signed-in users within the free daily allowance or an active plan, and may be rate-limited or withdrawn to prevent abuse. If you enable workspace sync while signed in, workspace content and optional key bags may be stored on our Cloudflare backend for that account.</p>
    <h2>Plans and payments</h2>
    <p>Plans bought with Telegram Stars run for the stated number of days from purchase and do not renew automatically. TON payments are verified on-chain against the order memo you are shown. Refunds for Stars follow Telegram's policy; for billing problems contact support@luminarasuite.com.</p>
    <h2>Acceptable use</h2>
    <p>Do not use the service to attack, scrape abusively, or misrepresent third parties, and do not attempt to extract hosted credentials. We may suspend access for abuse.</p>
    <h2>Open source and trademarks</h2>
    <p>The Luminara Suite source code is licensed under the GNU AGPL-3.0. "Luminara", "Luminara Suite" and the Luminara logo are trademarks of Luminara Digital Agency and are not covered by the code license.</p>
    <h2>Liability</h2>
    <p>The service is provided "as is". To the extent permitted by law, Luminara Digital Agency is not liable for indirect or consequential losses arising from use of the service.</p>
    <h2>Privacy</h2>
    <p>Personal data is handled as described in the <a href="/privacy">Privacy Policy</a>.</p>
  </main>
  <footer>&copy; 2026 Luminara Digital Agency · Luminara Suite</footer>
</body>
</html>
`;
